name: deploy

on:
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3"
      - name: Install OctoDNS
        run: pip install 'octodns==0.9.21' 'octodns-cloudflare==0.0.2'
      - name: Sync w/ production DNS providers
        run: octodns-sync --config-file config/production.yaml --doit
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
